FROM python:3.10-slim

# 安裝 Tesseract-OCR 與相關語言包
RUN apt-get update && apt-get install -y \
    tesseract-ocr \
    tesseract-ocr-chi-tra \
    tesseract-ocr-eng \
    libtesseract-dev \
    libjpeg-dev \
    libpng-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# 設定容器的工作目錄為 /app
WORKDIR /app

# 複製目前資料夾中的所有內容到容器的 /app
COPY . .

# 安裝 Python 套件
RUN pip install --no-cache-dir -r requirements.txt

# 開放容器內的 5000 port
EXPOSE 5000

# 執行主程式
CMD ["python", "app.py"]
